version: 2
updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/sic_backend_mvp_jwt_sqlite"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "duespark-team"
    assignees:
      - "duespark-team"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/sic_app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "duespark-team"
    assignees:
      - "duespark-team"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for React
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "duespark-team"
    assignees:
      - "duespark-team"

  # Docker
  - package-ecosystem: "docker"
    directory: "/sic_backend_mvp_jwt_sqlite"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "duespark-team"
    assignees:
      - "duespark-team"

  - package-ecosystem: "docker"
    directory: "/sic_app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "duespark-team"
    assignees:
      - "duespark-team"