services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: duespark
      POSTGRES_USER: duespark
      POSTGRES_PASSWORD: duespark
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: sic_backend_mvp_jwt_sqlite/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://duespark:duespark@db:5432/duespark
      SECRET_KEY: change-me
      PYTHONPATH: /app
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-}
      STRIPE_CLIENT_ID: ${STRIPE_CLIENT_ID:-}
      STRIPE_REDIRECT_URI: ${STRIPE_REDIRECT_URI:-http://localhost:8000/integrations/stripe/callback}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      STRIPE_API_VERSION: ${STRIPE_API_VERSION:-2023-10-16}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:-http://localhost:8000}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: sh -c "python init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  test:
    build:
      context: .
      dockerfile: sic_backend_mvp_jwt_sqlite/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://duespark:duespark@db:5432/duespark
      SECRET_KEY: change-me
      PYTHONPATH: /app
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-}
      STRIPE_CLIENT_ID: ${STRIPE_CLIENT_ID:-}
      STRIPE_REDIRECT_URI: ${STRIPE_REDIRECT_URI:-http://localhost:8000/integrations/stripe/callback}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      STRIPE_API_VERSION: ${STRIPE_API_VERSION:-2023-10-16}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:-http://localhost:8000}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python init_db.py && pytest -q"

volumes:
  pgdata:
