# DueSpark Backend - Fly.io Configuration
# Documentation: https://fly.io/docs/reference/configuration/

app = "duespark-backend"
primary_region = "iad"  # Washington DC - change based on your target audience

# Build configuration
[build]
  dockerfile = "sic_backend_mvp_jwt_sqlite/Dockerfile.production"

# Environment variables (non-sensitive)
[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  # Production optimizations
  PYTHONDONTWRITEBYTECODE = "1"
  PYTHONUNBUFFERED = "1"
  # Application settings
  APP_ENV = "production"
  LOG_LEVEL = "info"
  # Redis settings (optional - will use memory cache if not available)
  REDIS_URL = ""
  # Email provider (set via secrets)
  EMAIL_PROVIDER = "postmark"
  # Scheduler settings
  SCHEDULER_BATCH_SIZE = "200"
  ADAPTIVE_ENABLE = "true"
  # Rate limiting
  RATE_LIMIT_REQUESTS_PER_MINUTE = "60"
  RATE_LIMIT_REQUESTS_PER_HOUR = "1000"

# HTTP service configuration
[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Health checks
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false

# VM configuration
[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1"

# Machine configuration
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Auto-scaling configuration
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3

# Deployment configuration
[deploy]
  release_command = "echo 'Deployment starting...'"
  strategy = "rolling"

# Metrics (optional)
[metrics]
  port = 9091
  path = "/metrics"

# File system mounts (for logs and temporary files)
[[mounts]]
  source = "duespark_data"
  destination = "/app/logs"

# Resource limits and requests
[resource]
  memory = "1gb"
  cpu = "1x"

# Regional configuration (deploy to multiple regions)
# Uncomment and modify for multi-region deployment
# [[regions]]
#   primary = "iad"     # US East (Virginia)
#   backup = ["lax"]    # US West (Los Angeles)

# Secrets (set via `flyctl secrets set`)
# Don't put actual secrets here - use flyctl commands:
# flyctl secrets set SECRET_KEY=your-secret-key
# flyctl secrets set DATABASE_URL=postgres://...
# flyctl secrets set STRIPE_SECRET_KEY=sk_...
# flyctl secrets set POSTMARK_SERVER_TOKEN=...

# PostgreSQL addon will be created separately with:
# flyctl postgres create --name duespark-db --region iad