import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'DueSpark Documentation',
  tagline: 'Smart Invoice Management & Automated Payment Reminders',
  favicon: 'img/favicon.ico',

  // SEO metadata
  customFields: {
    description: 'Complete documentation for DueSpark - the intelligent invoice management platform with automated payment reminders, client management, and powerful analytics.',
  },

  // Site metadata
  metadata: [
    {name: 'keywords', content: 'invoice management, automated reminders, payment processing, API documentation, DueSpark'},
    {name: 'author', content: 'DueSpark Team'},
    {property: 'og:type', content: 'website'},
    {property: 'og:description', content: 'Complete documentation for DueSpark - intelligent invoice management with automated reminders'},
    {property: 'twitter:card', content: 'summary_large_image'},
  ],

  // Set the production url of your site here
  url: 'https://docs.duespark.com',
  // Set the /<baseUrl>/ pathname under which your site is served
  // For custom domain, use '/'
  baseUrl: '/',

  // GitHub pages deployment config.
  organizationName: 'duespark', // Usually your GitHub org/user name.
  projectName: 'duespark', // Usually your repo name.

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  plugins: [
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: "api", // plugin id
        docsPluginId: "classic", // configured for preset-classic
        config: {
          duespark: {
            specPath: "static/api/openapi.json", // path to OpenAPI spec (generated by deployment)
            outputDir: "docs/api", // output directory for MDX files
            sidebarOptions: {
              groupPathsBy: "tag",
              categoryLinkSource: "tag"
            },
          },
        }
      },
    ]
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl: 'https://github.com/duespark/duespark/tree/main/docs/',
          docItemComponent: "@theme/ApiItem", // Derived from docusaurus-theme-openapi
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          editUrl: 'https://github.com/duespark/duespark/tree/main/docs/',
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: ["docusaurus-theme-openapi-docs"], // export theme components

  themeConfig: {
    // Replace with your project's social card
    image: 'img/duespark-social-card.jpg',
    navbar: {
      title: 'DueSpark',
      logo: {
        alt: 'DueSpark Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'tutorialSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          to: '/docs/api',
          label: 'API Reference',
          position: 'left',
        },
        {to: '/blog', label: 'Blog', position: 'left'},
        {
          href: 'https://app.duespark.com',
          label: 'Try DueSpark',
          position: 'right',
        },
        {
          href: 'https://github.com/duespark/duespark',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Overview',
              to: '/docs/overview',
            },
            {
              label: 'Quickstart',
              to: '/docs/quickstart',
            },
            {
              label: 'API Reference',
              to: '/docs/api',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'GitHub Discussions',
              href: 'https://github.com/duespark/duespark/discussions',
            },
            {
              label: 'Issues',
              href: 'https://github.com/duespark/duespark/issues',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'Blog',
              to: '/blog',
            },
            {
              label: 'GitHub',
              href: 'https://github.com/duespark/duespark',
            },
            {
              label: 'Try DueSpark',
              href: 'https://app.duespark.com',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} DueSpark. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'diff', 'json', 'python', 'javascript', 'typescript'],
    },
    // Search configuration - Algolia (configure after deployment)
    // algolia: {
    //   appId: 'YOUR_APP_ID',
    //   apiKey: 'YOUR_SEARCH_API_KEY',
    //   indexName: 'duespark-docs',
    //   contextualSearch: true,
    //   searchPagePath: 'search',
    // },
    colorMode: {
      defaultMode: 'light',
      disableSwitch: false,
      respectPrefersColorScheme: true,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;